#!/bin/bash -ex

[[ ! "$DISTRO" =~ ^osx: ]] && export CFLAGS=-coverage
[[ ! "$DISTRO" =~ ^osx: ]] && export LDFLAGS=-lgcov

autoreconf -if

mkdir build
cd build

if ! ../configure --prefix=/usr --libdir=/usr/lib64 --disable-openmp; then
  cat ./config.log
  exit 1
fi

make -j8 -k check V=1 TESTS=

if ! make -j8 check; then
  cat ./tests/test-suite.log
  exit 1
fi

bash <(curl -s https://codecov.io/bash)
