#!/bin/bash -ex

prfx=$VECTORS/rfc7515_A

jose jws ver -i $prfx.1.jwsc -k $prfx.1.jwk
! jose jws ver -i $prfx.1.jwsc -k $prfx.2.jwk
! jose jws ver -i $prfx.1.jwsc -k $prfx.3.jwk
! jose jws ver -i $prfx.1.jwsc -k $prfx.4.jwk

! jose jws ver -i $prfx.2.jwsc -k $prfx.1.jwk
jose jws ver -i $prfx.2.jwsc -k $prfx.2.jwk
! jose jws ver -i $prfx.2.jwsc -k $prfx.3.jwk
! jose jws ver -i $prfx.2.jwsc -k $prfx.4.jwk

! jose jws ver -i $prfx.3.jwsc -k $prfx.1.jwk
! jose jws ver -i $prfx.3.jwsc -k $prfx.2.jwk
jose jws ver -i $prfx.3.jwsc -k $prfx.3.jwk
! jose jws ver -i $prfx.3.jwsc -k $prfx.4.jwk

! jose jws ver -i $prfx.4.jwsc -k $prfx.1.jwk
! jose jws ver -i $prfx.4.jwsc -k $prfx.2.jwk
! jose jws ver -i $prfx.4.jwsc -k $prfx.3.jwk
jose jws ver -i $prfx.4.jwsc -k $prfx.4.jwk

# We don't support alg = none

jose jws ver -i $prfx.6.jwsg -k $prfx.6.jwkset
jose jws ver -i $prfx.6.jwsg -k $prfx.6.jwkset -a
! jose jws ver -i $prfx.6.jwsg -k $prfx.6.jwkset -k $prfx.1.jwk -a

jose jws ver -i $prfx.6.jwsg -k $prfx.6.1.jwk
jose jws ver -i $prfx.6.jwsg -k $prfx.6.2.jwk
jose jws ver -i $prfx.6.jwsg -k $prfx.6.1.jwk -k $prfx.6.2.jwk
jose jws ver -i $prfx.6.jwsg -k $prfx.6.1.jwk -k $prfx.6.2.jwk -a
! jose jws ver -i $prfx.6.jwsg -k $prfx.6.1.jwk -k $prfx.6.2.jwk -k $prfx.1.jwk  -a

jose jws ver -i $prfx.7.jwsf -k $prfx.7.jwk


prfx=$VECTORS/rfc7520_4

jose jws ver -i $prfx.1.jwsc -k $prfx.1.jwk
jose jws ver -i $prfx.1.jwsf -k $prfx.1.jwk
jose jws ver -i $prfx.1.jwsg -k $prfx.1.jwk

jose jws ver -i $prfx.2.jwsc -k $prfx.2.jwk
jose jws ver -i $prfx.2.jwsf -k $prfx.2.jwk
jose jws ver -i $prfx.2.jwsg -k $prfx.2.jwk

jose jws ver -i $prfx.3.jwsc -k $prfx.3.jwk
jose jws ver -i $prfx.3.jwsf -k $prfx.3.jwk
jose jws ver -i $prfx.3.jwsg -k $prfx.3.jwk

jose jws ver -i $prfx.4.jwsc -k $prfx.4.jwk
jose jws ver -i $prfx.4.jwsf -k $prfx.4.jwk
jose jws ver -i $prfx.4.jwsg -k $prfx.4.jwk

jose jws ver -i $prfx.5.jwsc -I $prfx.5.payl -k $prfx.5.jwk
jose jws ver -i $prfx.5.jwsf -I $prfx.5.payl -k $prfx.5.jwk
jose jws ver -i $prfx.5.jwsg -I $prfx.5.payl -k $prfx.5.jwk

! jose jws ver -i $prfx.6.jwsc -k $prfx.6.jwk
jose jws ver -i $prfx.6.jwsf -k $prfx.6.jwk
jose jws ver -i $prfx.6.jwsg -k $prfx.6.jwk

! jose jws ver -i $prfx.7.jwsc -k $prfx.7.jwk
jose jws ver -i $prfx.7.jwsf -k $prfx.7.jwk
jose jws ver -i $prfx.7.jwsg -k $prfx.7.jwk

jose jws ver -i $prfx.8.jwsg -k $prfx.8.jwkset
jose jws ver -i $prfx.8.jwsg -k $prfx.8.1.jwk
jose jws ver -i $prfx.8.jwsg -k $prfx.8.2.jwk
jose jws ver -i $prfx.8.jwsg -k $prfx.8.3.jwk
