#!/bin/bash -ex

for f in ${srcdir:-.}/vectors/*.jwec; do
    cmpct=`cat $f`
    flat=`echo $f | sed 's|jwec|jwef|'`
    gen=`echo $f | sed 's|jwec|jweg|'`

    if [ -f $flat ]; then
    	[ `../cmd/jose jwe fmt -i $flat -c` == $cmpct ]
    	[ `../cmd/jose jwe fmt -i $flat | ../cmd/jose jwe fmt -i- -c` == $cmpct ]
    fi

    if [ -f $gen ]; then
    	[ `../cmd/jose jwe fmt -i $gen -c` == $cmpct ]
    	[ `../cmd/jose jwe fmt -i $gen | ../cmd/jose jwe fmt -i- -c` == $cmpct ]
    fi

    [ `../cmd/jose jwe fmt -i $f -c` == $cmpct ]
    [ `../cmd/jose jwe fmt -i $f | ../cmd/jose jwe fmt -i- -c` == $cmpct ]
done
