#!/bin/bash -ex

tmpdir=`mktemp -d`

function onexit() {
    rm -rf $tmpdir
}

trap exit ERR
trap onexit EXIT

for T in '{"alg":"ECDH"}' '{"alg":"ECDH","crv":"P-256"}' '{"kty":"EC","crv":"P-256"}'; do
    ../cmd/jose jwk gen -i "$T" -o $tmpdir/exc_a.jwk
    ../cmd/jose jwk gen -i "$T" -o $tmpdir/exc_b.jwk

    ../cmd/jose jwk pub -i $tmpdir/exc_a.jwk -o $tmpdir/exc_a.pub.jwk
    ../cmd/jose jwk pub -i $tmpdir/exc_b.jwk -o $tmpdir/exc_b.pub.jwk

    a=`../cmd/jose jwk exc -l $tmpdir/exc_a.jwk -r $tmpdir/exc_b.pub.jwk`
    b=`../cmd/jose jwk exc -l $tmpdir/exc_b.jwk -r $tmpdir/exc_a.pub.jwk`
    c=`../cmd/jose jwk exc -l $tmpdir/exc_a.jwk -r $tmpdir/exc_b.jwk`
    d=`../cmd/jose jwk exc -l $tmpdir/exc_b.jwk -r $tmpdir/exc_a.jwk`
    test "$a" == "$b"
    test "$c" == "$d"
    test "$a" == "$c"

    ! ../cmd/jose jwk exc -l $tmpdir/exc_a.pub.jwk -r $tmpdir/exc_b.jwk
    ! ../cmd/jose jwk exc -l $tmpdir/exc_b.pub.jwk -r $tmpdir/exc_a.jwk
    ! ../cmd/jose jwk exc -l $tmpdir/exc_a.pub.jwk -r $tmpdir/exc_b.pub.jwk
    ! ../cmd/jose jwk exc -l $tmpdir/exc_b.pub.jwk -r $tmpdir/exc_a.pub.jwk
done

../cmd/jose jwk gen -i '{"alg":"ECDH","crv":"P-384"}' -o $tmpdir/exc_c.jwk
! ../cmd/jose jwk exc -l $tmpdir/exc_c.jwk -r $tmpdir/exc_a.pub.jwk

../cmd/jose jwk gen -i '{"kty":"EC","crv":"P-384"}' -o $tmpdir/exc_c.jwk
! ../cmd/jose jwk exc -l $tmpdir/exc_c.jwk -r $tmpdir/exc_a.pub.jwk

../cmd/jose jwk gen -i '{ "alg": "ES256" }' -o $tmpdir/exc_c.jwk
! ../cmd/jose jwk exc -l $tmpdir/exc_c.jwk -r $tmpdir/exc_a.pub.jwk

srv=`../cmd/jose jwk gen -i '{"alg":"ECMR"}'`
clt=`../cmd/jose jwk gen -i '{"alg":"ECMR"}'`
eph=`../cmd/jose jwk gen -i '{"alg":"ECMR"}'`

spb=`echo "$srv" | ../cmd/jose jwk pub -i-`
cpb=`echo "$clt" | ../cmd/jose jwk pub -i-`

key=`echo "$clt$spb" | ../cmd/jose jwk exc -l- -r-`
sub=`echo "$eph$spb" | ../cmd/jose jwk exc -l- -r- -i '{"alg":"ECMR"}'`
req=`echo "$cpb$eph" | ../cmd/jose jwk exc -l- -r- -i '{"alg":"ECMR"}'`
rep=`echo "$srv$req" | ../cmd/jose jwk exc -l- -r- -i '{"alg":"ECMR"}'`
rec=`echo "$rep$sub" | ../cmd/jose jwk exc -l- -r-`
echo "$key$rec" | jose fmt -j- -Oj- -OE
