#!/bin/bash -ex

[ "`echo -n | ../cmd/jose b64 dec -i-`" == "" ]
[ `echo -n "Zg" | ../cmd/jose b64 dec -i-` == "f" ]
[ `echo -n "Zm8" | ../cmd/jose b64 dec -i-` == "fo" ]
[ `echo -n "Zm9v" | ../cmd/jose b64 dec -i-` == "foo" ]
[ `echo -n "Zm9vYg" | ../cmd/jose b64 dec -i-` == "foob" ]
[ `echo -n "Zm9vYmE" | ../cmd/jose b64 dec -i-` == "fooba" ]
[ `echo -n "Zm9vYmFy" | ../cmd/jose b64 dec -i-` == "foobar" ]
