#!/bin/bash -ex

export PATH=../cmd:$PATH

jose jwk use -i '{}' -u encrypt
! jose jwk use -i '{}' -r -u encrypt

! jose jwk use -i '{"use": true}' -u encrypt
! jose jwk use -i '{"key_ops": []}' -u encrypt
! jose jwk use -i '{"key_ops": [true]}' -u encrypt

jose jwk use -i '{"use": "enc"}' -u encrypt
! jose jwk use -i '{"use": "sig"}' -u encrypt

jose jwk use -i '{"key_ops": ["encrypt", "decrypt"]}' -u encrypt
jose jwk use -i '{"key_ops": ["encrypt", "decrypt"]}' -u encrypt -u decrypt
jose jwk use -i '{"key_ops": ["encrypt", "decrypt"]}' -a -u encrypt -u decrypt
jose jwk use -i '{"key_ops": ["encrypt", "decrypt"]}' -u encrypt -u sign
! jose jwk use -i '{"key_ops": ["encrypt", "decrypt"]}' -u sign
! jose jwk use -i '{"key_ops": ["encrypt", "decrypt"]}' -a -u encrypt -u sign

jose jwk use -i '{"use": "sig", "key_ops": ["encrypt", "decrypt"]}' -u encrypt -u sign
jose jwk use -i '{"use": "sig", "key_ops": ["encrypt", "decrypt"]}' -a -u encrypt -u sign

! jose jwk use -i '{"use": "enc"}' -u deriveKey
! jose jwk use -i '{"use": "enc"}' -u deriveBits
! jose jwk use -i '{"use": "sig"}' -u deriveKey
! jose jwk use -i '{"use": "sig"}' -u deriveBits

jwkset=`jose jwk gen -i '{"keys":[{"alg":"A128KW"},{"alg":"ES256"}]}'`

[ "`jose jwk use -i "$jwkset" -u wrapKey -s -o-`" == "`jose fmt -j "$jwkset" -g keys -d 1 -Uo-`" ]
[ "`jose jwk use -i "$jwkset" -u verify -s -o-`" == "`jose fmt -j "$jwkset" -g keys -d 0 -Uo-`" ]
[ "`jose jwk use -i "$jwkset" -u wrapKey -o-`" == "`jose fmt -j "$jwkset" -g keys -g 0 -o-`" ]
[ "`jose jwk use -i "$jwkset" -u verify -o-`" == "`jose fmt -j "$jwkset" -g keys -g 1 -o-`" ]
jose jwk use -i "$jwkset" -u verify -o-
