#!/bin/bash -ex

[ "`echo -n | ../cmd/jose b64 enc -I-`" == "" ]
[ `echo -n "f" | ../cmd/jose b64 enc -I-` == "Zg" ]
[ `echo -n "fo" | ../cmd/jose b64 enc -I-` == "Zm8" ]
[ `echo -n "foo" | ../cmd/jose b64 enc -I-` == "Zm9v" ]
[ `echo -n "foob" | ../cmd/jose b64 enc -I-` == "Zm9vYg" ]
[ `echo -n "fooba" | ../cmd/jose b64 enc -I-` == "Zm9vYmE" ]
[ `echo -n "foobar" | ../cmd/jose b64 enc -I-` == "Zm9vYmFy" ]
