#!/bin/bash -ex

[ "`echo -n | jose b64 enc -I-`" == "" ]
[ `echo -n "f" | jose b64 enc -I-` == "Zg" ]
[ `echo -n "fo" | jose b64 enc -I-` == "Zm8" ]
[ `echo -n "foo" | jose b64 enc -I-` == "Zm9v" ]
[ `echo -n "foob" | jose b64 enc -I-` == "Zm9vYg" ]
[ `echo -n "fooba" | jose b64 enc -I-` == "Zm9vYmE" ]
[ `echo -n "foobar" | jose b64 enc -I-` == "Zm9vYmFy" ]
