#!/bin/bash -x

trap 'exit' ERR

prfx=${srcdir}/tests/vectors/rfc7515_A

cmd/jose ver -i $prfx.1.jwsc -k $prfx.1.jwk

cmd/jose ver -i $prfx.2.jwsc -k $prfx.2.jwk

cmd/jose ver -i $prfx.3.jwsc -k $prfx.3.jwk

cmd/jose ver -i $prfx.4.jwsc -k $prfx.4.jwk

# We don't support alg = none

cmd/jose ver -i $prfx.6.jwsg -k $prfx.6.jwkset
cmd/jose ver -i $prfx.6.jwsg -k $prfx.6.1.jwk
cmd/jose ver -i $prfx.6.jwsg -k $prfx.6.2.jwk
cmd/jose ver -i $prfx.6.jwsg -k $prfx.6.1.jwk $prfx.6.2.jwk
cmd/jose ver -a -i $prfx.6.jwsg -k $prfx.6.jwkset
! cmd/jose ver -a -i $prfx.6.jwsg -k $prfx.6.jwkset -k $prfx.1.jwk
cmd/jose ver -a -i $prfx.6.jwsg -k $prfx.6.1.jwk -k $prfx.6.2.jwk
! cmd/jose ver -a -i $prfx.6.jwsg -k $prfx.6.1.jwk -k $prfx.6.2.jwk -k $prfx.1.jwk

cmd/jose ver -i $prfx.7.jwsf -k $prfx.7.jwk
