#!/bin/bash -x

trap 'exit' ERR

prfx=${srcdir}/tests/vectors/rfc7520_4

cmd/jose ver -i $prfx.1.jwsc -k $prfx.1.jwk
cmd/jose ver -i $prfx.1.jwsf -k $prfx.1.jwk
cmd/jose ver -i $prfx.1.jwsg -k $prfx.1.jwk

cmd/jose ver -i $prfx.2.jwsc -k $prfx.2.jwk
cmd/jose ver -i $prfx.2.jwsf -k $prfx.2.jwk
cmd/jose ver -i $prfx.2.jwsg -k $prfx.2.jwk

cmd/jose ver -i $prfx.3.jwsc -k $prfx.3.jwk
cmd/jose ver -i $prfx.3.jwsf -k $prfx.3.jwk
cmd/jose ver -i $prfx.3.jwsg -k $prfx.3.jwk

cmd/jose ver -i $prfx.4.jwsc -k $prfx.4.jwk
cmd/jose ver -i $prfx.4.jwsf -k $prfx.4.jwk
cmd/jose ver -i $prfx.4.jwsg -k $prfx.4.jwk

cmd/jose ver -i $prfx.5.jwsc -d $prfx.5.payl -k $prfx.5.jwk
cmd/jose ver -i $prfx.5.jwsf -d $prfx.5.payl -k $prfx.5.jwk
cmd/jose ver -i $prfx.5.jwsg -d $prfx.5.payl -k $prfx.5.jwk

! cmd/jose ver -i $prfx.6.jwsc -k $prfx.6.jwk
cmd/jose ver -i $prfx.6.jwsf -k $prfx.6.jwk
cmd/jose ver -i $prfx.6.jwsg -k $prfx.6.jwk

! cmd/jose ver -i $prfx.7.jwsc -k $prfx.7.jwk
cmd/jose ver -i $prfx.7.jwsf -k $prfx.7.jwk
cmd/jose ver -i $prfx.7.jwsg -k $prfx.7.jwk

cmd/jose ver -i $prfx.8.jwsg -k $prfx.8.jwkset
cmd/jose ver -i $prfx.8.jwsg -k $prfx.8.1.jwk
cmd/jose ver -i $prfx.8.jwsg -k $prfx.8.2.jwk
cmd/jose ver -i $prfx.8.jwsg -k $prfx.8.3.jwk
