.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "JOSE\-JWS\-FMT" "1" "June 2017" "" ""
.
.SH "NAME"
\fBjose\-jws\-fmt\fR \- Converts a JWS between serialization formats
.
.SH "SYNOPSIS"
\fBjose jws fmt\fR \-i JWS [\-I PAY] [\-o JWS] [\-O PAY] [\-c]
.
.SH "OVERVIEW"
The \fBjose jws fmt\fR command converts a JWS into alternative serialization formats\. For example, it can:
.
.IP "1." 4
Attach payload to a detached JWS\.
.
.IP "2." 4
Detach payload from a JWS\.
.
.IP "3." 4
Convert JWS Compact Serialization to JWS JSON Serialization\.
.
.IP "4." 4
Convert JWS JSON Serialization to JWS Compact Serialization\.
.
.IP "" 0
.
.SH "OPTIONS"
.
.TP
\fB\-i\fR \fIJSON\fR, \fB\-\-input\fR=\fIJSON\fR
Parse JWS from JSON
.
.TP
\fB\-i\fR \fIFILE\fR, \fB\-\-input\fR=\fIFILE\fR
Read JWS from FILE
.
.TP
\fB\-i\fR \-, \fB\-\-input\fR=\-
Read JWS from standard input
.
.TP
\fB\-I\fR \fIFILE\fR, \fB\-\-detached\fR=\fIFILE\fR
Read decoded payload from FILE
.
.TP
\fB\-I\fR \-, \fB\-\-detached\fR=\-
Read decoded payload from standard input
.
.TP
\fB\-o\fR \fIFILE\fR, \fB\-\-output\fR=\fIFILE\fR
Write JWS to FILE
.
.TP
\fB\-o\fR \-, \fB\-\-output\fR=\-
Write JWS to stdout (default)
.
.TP
\fB\-O\fR \fIFILE\fR, \fB\-\-detach\fR=\fIFILE\fR
Detach payload and decode to FILE
.
.TP
\fB\-O\fR \-, \fB\-\-detach\fR=\-
Detach payload and decode to standard output
.
.TP
\fB\-c\fR, \fB\-\-compact\fR
Output JWS using compact serialization
.
.SH "EXAMPLES"
Attach payload to a detached JWS and emit JWS Compact Serialization:
.
.IP "" 4
.
.nf

$ jose jws fmt \-i msg\.jws \-I msg\.txt \-o compact\.jws \-c
.
.fi
.
.IP "" 0
.
.P
Detach payload from a JWS:
.
.IP "" 4
.
.nf

$ jose jws fmt \-i msg\.jws \-o detached\.jws \-O msg\.txt
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Nathaniel McCallum <npmccallum@redhat\.com>
.
.SH "SEE ALSO"
\fBjose\-jws\-sig\fR(1), \fBjose\-jws\-ver\fR(1)
