.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "JOSE" "1" "May 2017" "" ""
.
.SH "NAME"
\fBjose\fR \- Toolkit for performing JSON Object Signing and Encryption
.
.SH "SYNOPSIS"
\fBjose alg\fR [\-k KIND]
.
.P
\fBjose b64 dec\fR \-i B64 [\-O BIN]
.
.P
\fBjose b64 enc\fR \-I BIN [\-o B64]
.
.P
\fBjose jwe dec\fR \-i JWE [\-I CT] \-k JWK [\-p] [\-O PT]
.
.P
\fBjose jwe enc\fR [\-i JWE] \-I PT \-k JWK [\-p] [\-r RCP] [\-o JWE] [\-O CT] [\-c]
.
.P
\fBjose jwe fmt\fR \-i JWE [\-I CT] [\-o JWE] [\-O CT] [\-c]
.
.P
\fBjose jwk exc\fR [\-i JWK] \-l JWK \-r JWK [\-o JWK]
.
.P
\fBjose jwk gen\fR \-i JWK [\-o JWK]
.
.P
\fBjose jwk pub\fR \-i JWK [\-o JWK]
.
.P
\fBjose jwk thp\fR \-i JWK [\-a ALG] [\-o THP]
.
.P
\fBjose jwk use\fR \-i JWK [\-a] [\-r] \-u OP
.
.P
\fBjose jws fmt\fR \-i JWS [\-I PAY] [\-o JWS] [\-O PAY] [\-c]
.
.P
\fBjose jws sig\fR [\-i JWS] [\-I PAY] [\-s SIG] \-k JWK [\-o JWS] [\-O PAY] [\-c]
.
.P
\fBjose jws ver\fR \-i JWS [\-I PAY] \-k JWK [\-O PAY] [\-a]
.
.SH "OVERVIEW"
José is a C\-language implementation of the Javascript Object Signing and Encryption standards\. Specifically, José aims towards implementing the following standards:
.
.IP "\(bu" 4
RFC 7515 \- JSON Web Signature (JWS)
.
.IP "\(bu" 4
RFC 7516 \- JSON Web Encryption (JWE)
.
.IP "\(bu" 4
RFC 7517 \- JSON Web Key (JWK)
.
.IP "\(bu" 4
RFC 7518 \- JSON Web Algorithms (JWA)
.
.IP "\(bu" 4
RFC 7519 \- JSON Web Token (JWT)
.
.IP "\(bu" 4
RFC 7520 \- Examples of Protecting Content Using JOSE
.
.IP "\(bu" 4
RFC 7638 \- JSON Web Key (JWK) Thumbprint
.
.IP "" 0
.
.P
The José command line utility provides facilities for the following:
.
.IP "\(bu" 4
URL\-safe Base64 Encoding & Decoding
.
.IP "\(bu" 4
Key Generation and Management
.
.IP "\(bu" 4
Encryption & Decryption
.
.IP "\(bu" 4
Signing & Verification
.
.IP "" 0
.
.SH "AUTHOR"
Nathaniel McCallum <npmccallum@redhat\.com>
.
.SH "SEE ALSO"
\fBjose\-alg\fR(1), \fBjose\-b64\-dec\fR(1), \fBjose\-b64\-enc\fR(1), \fBjose\-jwe\-dec\fR(1), \fBjose\-jwe\-enc\fR(1), \fBjose\-jwe\-fmt\fR(1), \fBjose\-jwk\-exc\fR(1), \fBjose\-jwk\-gen\fR(1), \fBjose\-jwk\-pub\fR(1), \fBjose\-jwk\-thp\fR(1), \fBjose\-jwk\-use\fR(1), \fBjose\-jws\-fmt\fR(1), \fBjose\-jws\-sig\fR(1), \fBjose\-jws\-ver\fR(1)
