.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "JOSE\-JWS\-SIG" "1" "May 2017" "" ""
.
.SH "NAME"
\fBjose\-jws\-sig\fR \- Signs a payload using one or more JWKs
.
.SH "SYNOPSIS"
\fBjose jws sig\fR [\-i JWS] [\-I PAY] [\-s SIG] \-k JWK [\-o JWS] [\-O PAY] [\-c]
.
.SH "OVERVIEW"
The \fBjose jws sig\fR command signs a payload using one or more JWKs\. The payload can be provided either in its decoded form (\fB\-I\fR) or embedded in an existing JWS (\'\-i\')\.
.
.P
A detached JWS can be created by specifying the \fB\-O\fR option\. In this case, the decoded payload will be written to the output specified and will not be included in the JWS\.
.
.P
If only one key is used (\fB\-k\fR), the resulting JWS may be output in JWS Compact Serialization by using the \fB\-c\fR option\.
.
.P
This command uses a template based approach for constructing a JWS\. You can specify templates of the JWS itself (\fB\-i\fR) or for the JWS Signature Object (\fB\-r\fR)\. Attributes specified in either of these templates will appear unmodified in the output\. One exception to this rule is that the JWS Protected Header should be specified in its decoded form in the JWS Signature Object template\. This command will automatically encode it as part of the encryption process\.
.
.P
It is possible to specify an existing JWS as the JWS template input (\fB\-i\fR)\. This allows the addition of new signatures to an existing JWS\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-i\fR \fIJSON\fR, \fB\-\-input\fR=\fIJSON\fR : Parse JWS template from JSON
.
.IP "\(bu" 4
\fB\-i\fR \fIFILE\fR, \fB\-\-input\fR=\fIFILE\fR : Read JWS template from FILE
.
.IP "\(bu" 4
\fB\-i\fR \-, \fB\-\-input\fR=\- : Read JWS template from standard input
.
.IP "\(bu" 4
\fB\-I\fR \fIFILE\fR, \fB\-\-detached\fR=\fIFILE\fR Read decoded payload from FILE
.
.IP "\(bu" 4
\fB\-I\fR \-, \fB\-\-detached\fR=\- : Read decoded payload from standard input
.
.IP "\(bu" 4
\fB\-s\fR \fIJSON\fR, \fB\-\-signature\fR=\fIJSON\fR : Parse JWS signature template from JSON
.
.IP "\(bu" 4
\fB\-s\fR \fIFILE\fR, \fB\-\-signature\fR=\fIFILE\fR : Read JWS signature template from FILE
.
.IP "\(bu" 4
\fB\-s\fR \-, \fB\-\-signature\fR=\- : Read JWS signature template standard input
.
.IP "\(bu" 4
\fB\-k\fR \fIFILE\fR, \fB\-\-key\fR=\fIFILE\fR : Read JWK(Set) from FILE
.
.IP "\(bu" 4
\fB\-k\fR \-, \fB\-\-key\fR=\- : Read JWK(Set) from standard input
.
.IP "\(bu" 4
\fB\-o\fR \fIFILE\fR, \fB\-\-output\fR=\fIFILE\fR : Write JWS to FILE
.
.IP "\(bu" 4
\fB\-o\fR \-, \fB\-\-output\fR=\- : Write JWS to stdout (default)
.
.IP "\(bu" 4
\fB\-O\fR \fIFILE\fR, \fB\-\-detach\fR=\fIFILE\fR : Detach payload and decode to FILE
.
.IP "\(bu" 4
\fB\-O\fR \-, \fB\-\-detach\fR=\- : Detach payload and decode to standard output
.
.IP "\(bu" 4
\fB\-c\fR, \fB\-\-compact\fR : Output JWS using compact serialization
.
.IP "" 0
.
.SH "AUTHOR"
Nathaniel McCallum <npmccallum@redhat\.com>
.
.SH "SEE ALSO"
\fBjose\-jws\-sig\fR(1), \fBjose\-jws\-ver\fR(1)
