.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "JOSE\-JWE\-DEC" "1" "May 2017" "" ""
.
.SH "NAME"
\fBjose\-jwe\-dec\fR \- Decrypts a JWE using the supplied JWKs
.
.SH "SYNOPSIS"
\fBjose jwe dec\fR \-i JWE [\-I CT] \-k JWK [\-p] [\-O PT]
.
.SH "OVERVIEW"
The \fBjose jwe dec\fR command decrypts a JWE using one or more JWK (\fB\-k\fR) or password (\fB\-p\fR)\. Decryption succeeds if any key is able to perform decryption\.
.
.P
If the JWE is a detached JWE, meaning that the ciphertext is stored in binary form external to the JWE itself, the ciphertext can be loaded using the \fB\-I\fR parameter\.
.
.P
Please note that, when specifying the \fB\-O\fR option to output the plaintext, plaintext output begins before ciphertext validation\. Therefore, you must check the return value of the command before using the data\.
.
.SH "OPTIONS"
.
.TP
\fB\-i\fR \fIJSON\fR, \fB\-\-input\fR=\fIJSON\fR
Parse JWE from JSON
.
.TP
\fB\-i\fR \fIFILE\fR, \fB\-\-input\fR=\fIFILE\fR
Read JWE from FILE
.
.TP
\fB\-i\fR \-, \fB\-\-input\fR=\-
Read JWE from standard input
.
.TP
\fB\-I\fR \fIFILE\fR, \fB\-\-detached\fR=\fIFILE\fR
Read decoded ciphertext from FILE
.
.TP
\fB\-I\fR \-, \fB\-\-detached\fR=\-
Read decoded ciphertext from standard input
.
.TP
\fB\-p\fR, \fB\-\-password\fR
Prompt for a decryption password, if necessary
.
.TP
\fB\-k\fR \fIFILE\fR, \fB\-\-key\fR=\fIFILE\fR
Read JWK(Set) from FILE
.
.TP
\fB\-k\fR \-, \fB\-\-key=\-\fR
Read JWK(Set) from standard input
.
.TP
\fB\-O\fR \fIJSON\fR, \fB\-\-detach\fR=\fIJSON\fR
Parse JWE from JSON
.
.TP
\fB\-O\fR \fIFILE\fR, \fB\-\-detach\fR=\fIFILE\fR
Read JWE from FILE
.
.TP
\fB\-O\fR \-, \fB\-\-detach\fR=\-
Read JWE from standard input
.
.SH "EXAMPLES"
Decrypt a JWE with a JWK:
.
.IP "" 4
.
.nf

$ jose jwe dec \-i msg\.jwe \-k rsa\.key \-O msg\.txt
.
.fi
.
.IP "" 0
.
.P
Decrypt a JWE with a password:
.
.IP "" 4
.
.nf

$ jose jwe dec \-i msg\.jwe \-p \-O msg\.txt
Please enter decryption password:
.
.fi
.
.IP "" 0
.
.P
Decrypt a JWE with either of two JWKs:
.
.IP "" 4
.
.nf

$ jose jwe dec \-i msg\.jwe \-k ec\.jwk \-k rsa\.jwk \-O msg\.txt
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Nathaniel McCallum <npmccallum@redhat\.com>
.
.SH "SEE ALSO"
\fBjose\-jwe\-enc\fR(1), \fBjose\-jwe\-fmt\fR(1)
