.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "JOSE\-B64\-ENC" "1" "June 2017" "" ""
.
.SH "NAME"
\fBjose\-b64\-enc\fR \- Encodes binary data to URL\-safe Base64
.
.SH "SYNOPSIS"
\fBjose b64 enc\fR \-I BIN [\-o B64]
.
.SH "OVERVIEW"
The \fBjose b64 enc\fR command encodes binary data to URL\-safe Base64 format\.
.
.SH "OPTIONS"
.
.TP
\fB\-I\fR \fIFILE\fR, \fB\-\-binary\fR=\fIFILE\fR
Read binary data from FILE
.
.TP
\fB\-I\fR \-, \fB\-\-binary\fR=\-
Read binary data from standard input
.
.TP
\fB\-o\fR \fIFILE\fR, \fB\-\-base64\fR=\fIFILE\fR
Write Base64 (URL\-safe) to FILE
.
.TP
\fB\-o\fR \-, \fB\-\-base64\fR=\-
Write Base64 (URL\-safe) to standard output
.
.SH "EXAMPLES"
Encode a simple message:
.
.IP "" 4
.
.nf

$ echo "Hello, World" | jose b64 enc \-I\-
SGVsbG8sIFdvcmxkCg
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Nathaniel McCallum <npmccallum@redhat\.com>
.
.SH "SEE ALSO"
\fBjose\-b64\-dec\fR(1)
